# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Trans Patient Union at McGill
title-fr: Union des Patient Trans

title-displayed: Trans Patient Union <br> at McGill University
title-displayed-fr: Union des Patient Trans <br> à l'Université McGill

email: unionreptpu@gmail.com
reporting_email: reporting.tpu@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  "The Trans Patient Union is an advocacy and mutual aid collective by and for trans and nonbinary patients at McGill and in broader Tio’tia:ke (colonially known as Montreal)."

description_fr:
  "L'Union des patients lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, vestibulum mi nec, ultrices ipsum. Nulla nec purus feugiat, vestibulum"

baseurl: "" # the subpath of your site, e.g. /blog

# baseurl: "" # use this for development purposes

url: "https://transpatientunion.org" # the base hostname & protocol for your site, e.g. http://example.com

newsletter_url: "https://trans-patient-union.ck.page/48a5adc29e"

instagram_username: "transpatients"

# Build settings
theme: minima

plugins:
  - jekyll-feed

# Logo
logo: "assets/logo.png"

# header background
header-banner: "assets/tpu_banner_3.png"
# exclude
exclude: [_unused_layouts, _unused_sass, README.md]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
